import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Learn by Practice</h1>

        <p className={styles.description}>Get started by editing</p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Learn First Aid </h2>
            <p>It takes a second to save a life!</p>
          </a>

          <a className={styles.card}>
            <h2>Learn Something Else</h2>
            <p>I have no idea yet</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
